# Standards: 0.1
---
- name: Fact hammerspoon user
  set_fact:
    hammerspoon_user: "{{ hammerspoon_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - hammerspoon

- become: "{{ (hammerspoon_user != ansible_user_id) | bool }}"
  become_user: "{{ hammerspoon_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: hammerspoon
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - hammerspoon

- name: Remove quarantine flag
  register: hammerspoon_quarantine
  failed_when: hammerspoon_quarantine.rc != 0 and "No such xattr" not in hammerspoon_quarantine.stderr
  changed_when: hammerspoon_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/Hammerspoon.app
  tags:
    - hammerspoon

...
